/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

//    @Test
//    public void testRoll() {
//        int[] rolledArray = Library.roll(4);
//        assertNotNull(rolledArray);
//        assertEquals(4, rolledArray.length);
//        for (int num : rolledArray) {
//            assertTrue(num >= 1 && num <= 6);
//        }
//    }
//
//    @Test
//    public void testContainsDuplicates() {
//        int[] array = {1, 1, 2};
//        assertTrue(Library.containsDuplicates(array));
//
//        int[] noDuplicatesArray = {1, 2, 3};
//        assertFalse(Library.containsDuplicates(noDuplicatesArray));
//    }
//
//    @Test
//    public void testCalculateAverage() {
//        int[] array = {30, 30, 30};
//        double expectedAverage = 30.0;
//        assertEquals(expectedAverage, Library.calculateAverage(array));
//    }
//
//    @Test
//    public void testArraysOfArrays() {
//        int[][] weeklyMonthTemperatures = {
//                {66, 64, 58, 65, 71, 57, 60},
//                {57, 65, 65, 70, 72, 65, 51},
//                {55, 54, 60, 53, 59, 57, 61},
//                {65, 56, 55, 52, 55, 62, 57}
//        };
//        assertArrayEquals(weeklyMonthTemperatures[2], Library.arraysOfArrays(weeklyMonthTemperatures));
//    }

    @Test
    public void testAnalyzingWeather()
    {
       var analysis= new Library();

        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int max=72;
        int min=51;
        String missingTemperatures = "\nNever saw temperatures: 63 \n" +
                "Never saw temperatures: 67 \n" +
                "Never saw temperatures: 68 \n" +
                "Never saw temperatures: 69 ";

       assertEquals( "High:" + max + "\nLow:" + min + "\n"+ missingTemperatures ,analysis.analyzingWeather(weeklyMonthTemperatures));
    };




    @Test
    public void testTally()
    {
       var winner= new Library();
        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");

        assertEquals( "Bush received the most votes!",winner.tally(votes));
    }
}



