/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args) {
        Restaurant restaurant = new Restaurant("Delicious Eats", 4, 2);

        Review review1 = new Review("Alice", "Great food!", 5, restaurant);
        restaurant.addReview(review1);
        System.out.println(restaurant);

    }
}
