/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args) {
        Restaurant restaurant = new Restaurant("Delicious Eats", 4, 2);
        Shop shop = new Shop("Fashion Emporium", "Trendy clothes", 3);
        Theater theater = new Theater("Cineplex");

        theater.addMovie("Avengers: Endgame");
        theater.addMovie("The Lion King");

        theater.removeMovie("The Lion King");

        Review review1 = new Review("Alice", "Great food!", 5, restaurant);
        Review review2 = new Review("Jack", "Amazing food!", 3, restaurant);
        Review review3 = new Review("Bob", "Nice clothes collection.", 4, shop);
        Review review4 = new Review("Charlie", "Amazing movie!", 5, "Avengers: Endgame", theater);
        Review review5 = new Review("John", "Amazing movie!", 4, theater);


        restaurant.addReview(review1);
        restaurant.addReview(review2);
        shop.addReview(review3);
        theater.addReview(review4);
        theater.addReview(review5);

        System.out.println(restaurant);
        System.out.println(shop);
        System.out.println(theater);

    }
}
